---
- src: https://github.com/OULibraries/ansible-role-centos7
  version: v2016-10-17.0
  name: OULibraries.centos7

- src: https://github.com/OULibraries/ansible-role-repox
  version: v2016-10-17.1
  name: OULibraries.repox

- src: https://github.com/OULibraries/ansible-role-apache2
  version: v2016-10-17.0
  name: OULibraries.apache2

- src: https://github.com/OULibraries/ansible-role-mariadb
  version: v2016-09-26.0
  name: OULibraries.mariadb

- src: https://github.com/OULibraries/ansible-role-postfix-mta
  version: v2016-10-17.0
  name: OULibraries.postfix-mta

- src: https://github.com/OULibraries/ansible-role-ngrok
  version: v2016-04-08.0
  name: OULibraries.ngrok

- src: https://github.com/OULibraries/ansible-role-users
  version: v2016-08-10.0
  name: OULibraries.users
