---
- hosts: default
  sudo: yes
  vars_files:
    - my-vars.yml
  
  roles:
    - { role: OULibraries.centos7, tags: ["centos7"] }
    - { role: OULibraries.apache2, tags: ["apache2"] }
    - { role: OULibraries.postfix-mta, tags: ["postfix-mta"] }
    - { role: OULibraries.repox, tags: ["repox"] }
    - { role: OULibraries.ngrok, tags: ["ngrok"] }
    - { role: OULibraries.users, tags: ["users"] }

  tasks:
    - name: packages for development and testing
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - emacs
        - net-tools
