---
- name: install the repox war into tomcat
  copy:
    src: "{{ path.source }}/gui/target/repox.war"
    dest: "{{ path.tomcat }}/webapps/"
- name: replace default admin user
  template:
    src: "{{ path.playbook }}/users.xml.j2"
    dest: "{{ path.data }}/repoxData/configuration/users.xml"
