---
- name: packages for the repox installation
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - java
  - tomcat
  - mariadb-server
  - git
  - maven
  - patch
  - MySQL-python
- name: packages for development and testing
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - dkms
  - emacs
  - screen
  - net-tools
